// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.0
// source: payment.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PaymentStatus int32

const (
	PaymentStatus_PAYMENT_STATUS_PENDING   PaymentStatus = 0
	PaymentStatus_PAYMENT_STATUS_PAID      PaymentStatus = 1
	PaymentStatus_PAYMENT_STATUS_CANCELLED PaymentStatus = 2
	PaymentStatus_PAYMENT_STATUS_REFUNDED  PaymentStatus = 3
)

// Enum value maps for PaymentStatus.
var (
	PaymentStatus_name = map[int32]string{
		0: "PAYMENT_STATUS_PENDING",
		1: "PAYMENT_STATUS_PAID",
		2: "PAYMENT_STATUS_CANCELLED",
		3: "PAYMENT_STATUS_REFUNDED",
	}
	PaymentStatus_value = map[string]int32{
		"PAYMENT_STATUS_PENDING":   0,
		"PAYMENT_STATUS_PAID":      1,
		"PAYMENT_STATUS_CANCELLED": 2,
		"PAYMENT_STATUS_REFUNDED":  3,
	}
)

func (x PaymentStatus) Enum() *PaymentStatus {
	p := new(PaymentStatus)
	*p = x
	return p
}

func (x PaymentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaymentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_payment_proto_enumTypes[0].Descriptor()
}

func (PaymentStatus) Type() protoreflect.EnumType {
	return &file_payment_proto_enumTypes[0]
}

func (x PaymentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaymentStatus.Descriptor instead.
func (PaymentStatus) EnumDescriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{0}
}

type PaymentCreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Amount        float32                `protobuf:"fixed32,1,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentCreateRequest) Reset() {
	*x = PaymentCreateRequest{}
	mi := &file_payment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentCreateRequest) ProtoMessage() {}

func (x *PaymentCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentCreateRequest.ProtoReflect.Descriptor instead.
func (*PaymentCreateRequest) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{0}
}

func (x *PaymentCreateRequest) GetAmount() float32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type PaymentCreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Amount        float32                `protobuf:"fixed32,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Status        PaymentStatus          `protobuf:"varint,3,opt,name=status,proto3,enum=PaymentStatus" json:"status,omitempty"`
	InvoiceID     string                 `protobuf:"bytes,4,opt,name=invoiceID,proto3" json:"invoiceID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentCreateResponse) Reset() {
	*x = PaymentCreateResponse{}
	mi := &file_payment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentCreateResponse) ProtoMessage() {}

func (x *PaymentCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentCreateResponse.ProtoReflect.Descriptor instead.
func (*PaymentCreateResponse) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{1}
}

func (x *PaymentCreateResponse) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *PaymentCreateResponse) GetAmount() float32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *PaymentCreateResponse) GetStatus() PaymentStatus {
	if x != nil {
		return x.Status
	}
	return PaymentStatus_PAYMENT_STATUS_PENDING
}

func (x *PaymentCreateResponse) GetInvoiceID() string {
	if x != nil {
		return x.InvoiceID
	}
	return ""
}

type PaymentCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentCheckRequest) Reset() {
	*x = PaymentCheckRequest{}
	mi := &file_payment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentCheckRequest) ProtoMessage() {}

func (x *PaymentCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentCheckRequest.ProtoReflect.Descriptor instead.
func (*PaymentCheckRequest) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{2}
}

func (x *PaymentCheckRequest) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

type PaymentCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Amount        float32                `protobuf:"fixed32,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Status        PaymentStatus          `protobuf:"varint,3,opt,name=status,proto3,enum=PaymentStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentCheckResponse) Reset() {
	*x = PaymentCheckResponse{}
	mi := &file_payment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentCheckResponse) ProtoMessage() {}

func (x *PaymentCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentCheckResponse.ProtoReflect.Descriptor instead.
func (*PaymentCheckResponse) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{3}
}

func (x *PaymentCheckResponse) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *PaymentCheckResponse) GetAmount() float32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *PaymentCheckResponse) GetStatus() PaymentStatus {
	if x != nil {
		return x.Status
	}
	return PaymentStatus_PAYMENT_STATUS_PENDING
}

var File_payment_proto protoreflect.FileDescriptor

const file_payment_proto_rawDesc = "" +
	"\n" +
	"\rpayment.proto\".\n" +
	"\x14PaymentCreateRequest\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\x02R\x06amount\"\x87\x01\n" +
	"\x15PaymentCreateResponse\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x02R\x06amount\x12&\n" +
	"\x06status\x18\x03 \x01(\x0e2\x0e.PaymentStatusR\x06status\x12\x1c\n" +
	"\tinvoiceID\x18\x04 \x01(\tR\tinvoiceID\"'\n" +
	"\x13PaymentCheckRequest\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\"h\n" +
	"\x14PaymentCheckResponse\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x02R\x06amount\x12&\n" +
	"\x06status\x18\x03 \x01(\x0e2\x0e.PaymentStatusR\x06status*\x7f\n" +
	"\rPaymentStatus\x12\x1a\n" +
	"\x16PAYMENT_STATUS_PENDING\x10\x00\x12\x17\n" +
	"\x13PAYMENT_STATUS_PAID\x10\x01\x12\x1c\n" +
	"\x18PAYMENT_STATUS_CANCELLED\x10\x02\x12\x1b\n" +
	"\x17PAYMENT_STATUS_REFUNDED\x10\x032\xbd\x01\n" +
	"\x0ePaymentService\x127\n" +
	"\x06Create\x12\x15.PaymentCreateRequest\x1a\x16.PaymentCreateResponse\x124\n" +
	"\x05Check\x12\x14.PaymentCheckRequest\x1a\x15.PaymentCheckResponse\x12<\n" +
	"\vCheckStream\x12\x14.PaymentCheckRequest\x1a\x15.PaymentCheckResponse0\x01B\x03Z\x01.b\x06proto3"

var (
	file_payment_proto_rawDescOnce sync.Once
	file_payment_proto_rawDescData []byte
)

func file_payment_proto_rawDescGZIP() []byte {
	file_payment_proto_rawDescOnce.Do(func() {
		file_payment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_payment_proto_rawDesc), len(file_payment_proto_rawDesc)))
	})
	return file_payment_proto_rawDescData
}

var file_payment_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_payment_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_payment_proto_goTypes = []any{
	(PaymentStatus)(0),            // 0: PaymentStatus
	(*PaymentCreateRequest)(nil),  // 1: PaymentCreateRequest
	(*PaymentCreateResponse)(nil), // 2: PaymentCreateResponse
	(*PaymentCheckRequest)(nil),   // 3: PaymentCheckRequest
	(*PaymentCheckResponse)(nil),  // 4: PaymentCheckResponse
}
var file_payment_proto_depIdxs = []int32{
	0, // 0: PaymentCreateResponse.status:type_name -> PaymentStatus
	0, // 1: PaymentCheckResponse.status:type_name -> PaymentStatus
	1, // 2: PaymentService.Create:input_type -> PaymentCreateRequest
	3, // 3: PaymentService.Check:input_type -> PaymentCheckRequest
	3, // 4: PaymentService.CheckStream:input_type -> PaymentCheckRequest
	2, // 5: PaymentService.Create:output_type -> PaymentCreateResponse
	4, // 6: PaymentService.Check:output_type -> PaymentCheckResponse
	4, // 7: PaymentService.CheckStream:output_type -> PaymentCheckResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_payment_proto_init() }
func file_payment_proto_init() {
	if File_payment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_payment_proto_rawDesc), len(file_payment_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_payment_proto_goTypes,
		DependencyIndexes: file_payment_proto_depIdxs,
		EnumInfos:         file_payment_proto_enumTypes,
		MessageInfos:      file_payment_proto_msgTypes,
	}.Build()
	File_payment_proto = out.File
	file_payment_proto_goTypes = nil
	file_payment_proto_depIdxs = nil
}
