// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.0
// source: payment.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PaymentStatus int32

const (
	PaymentStatus_PAYMENT_STATUS_PENDING   PaymentStatus = 0
	PaymentStatus_PAYMENT_STATUS_PAID      PaymentStatus = 1
	PaymentStatus_PAYMENT_STATUS_CANCELLED PaymentStatus = 2
	PaymentStatus_PAYMENT_STATUS_REFUNDED  PaymentStatus = 3
)

// Enum value maps for PaymentStatus.
var (
	PaymentStatus_name = map[int32]string{
		0: "PAYMENT_STATUS_PENDING",
		1: "PAYMENT_STATUS_PAID",
		2: "PAYMENT_STATUS_CANCELLED",
		3: "PAYMENT_STATUS_REFUNDED",
	}
	PaymentStatus_value = map[string]int32{
		"PAYMENT_STATUS_PENDING":   0,
		"PAYMENT_STATUS_PAID":      1,
		"PAYMENT_STATUS_CANCELLED": 2,
		"PAYMENT_STATUS_REFUNDED":  3,
	}
)

func (x PaymentStatus) Enum() *PaymentStatus {
	p := new(PaymentStatus)
	*p = x
	return p
}

func (x PaymentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaymentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_payment_proto_enumTypes[0].Descriptor()
}

func (PaymentStatus) Type() protoreflect.EnumType {
	return &file_payment_proto_enumTypes[0]
}

func (x PaymentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaymentStatus.Descriptor instead.
func (PaymentStatus) EnumDescriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{0}
}

type PaymentType int32

const (
	PaymentType_PAYMENT_TYPE_QPAY      PaymentType = 0
	PaymentType_PAYMENT_TYPE_TOKIPAY   PaymentType = 1
	PaymentType_PAYMENT_TYPE_MONPAY    PaymentType = 2
	PaymentType_PAYMENT_TYPE_GOLOMT    PaymentType = 3
	PaymentType_PAYMENT_TYPE_SOCIALPAY PaymentType = 4
	PaymentType_PAYMENT_TYPE_STOREPAY  PaymentType = 5
	PaymentType_PAYMENT_TYPE_POCKET    PaymentType = 6
	PaymentType_PAYMENT_TYPE_SIMPLE    PaymentType = 7
	PaymentType_PAYMENT_TYPE_BALC      PaymentType = 8
)

// Enum value maps for PaymentType.
var (
	PaymentType_name = map[int32]string{
		0: "PAYMENT_TYPE_QPAY",
		1: "PAYMENT_TYPE_TOKIPAY",
		2: "PAYMENT_TYPE_MONPAY",
		3: "PAYMENT_TYPE_GOLOMT",
		4: "PAYMENT_TYPE_SOCIALPAY",
		5: "PAYMENT_TYPE_STOREPAY",
		6: "PAYMENT_TYPE_POCKET",
		7: "PAYMENT_TYPE_SIMPLE",
		8: "PAYMENT_TYPE_BALC",
	}
	PaymentType_value = map[string]int32{
		"PAYMENT_TYPE_QPAY":      0,
		"PAYMENT_TYPE_TOKIPAY":   1,
		"PAYMENT_TYPE_MONPAY":    2,
		"PAYMENT_TYPE_GOLOMT":    3,
		"PAYMENT_TYPE_SOCIALPAY": 4,
		"PAYMENT_TYPE_STOREPAY":  5,
		"PAYMENT_TYPE_POCKET":    6,
		"PAYMENT_TYPE_SIMPLE":    7,
		"PAYMENT_TYPE_BALC":      8,
	}
)

func (x PaymentType) Enum() *PaymentType {
	p := new(PaymentType)
	*p = x
	return p
}

func (x PaymentType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaymentType) Descriptor() protoreflect.EnumDescriptor {
	return file_payment_proto_enumTypes[1].Descriptor()
}

func (PaymentType) Type() protoreflect.EnumType {
	return &file_payment_proto_enumTypes[1]
}

func (x PaymentType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaymentType.Descriptor instead.
func (PaymentType) EnumDescriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{1}
}

type PaymentCreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Amount        float32                `protobuf:"fixed32,1,opt,name=amount,proto3" json:"amount,omitempty"`
	Type          PaymentType            `protobuf:"varint,5,opt,name=type,proto3,enum=PaymentType" json:"type,omitempty"`
	MerchantId    uint64                 `protobuf:"varint,6,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	Phone         string                 `protobuf:"bytes,7,opt,name=phone,proto3" json:"phone,omitempty"`
	CustomerId    uint64                 `protobuf:"varint,8,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	Note          string                 `protobuf:"bytes,9,opt,name=note,proto3" json:"note,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentCreateRequest) Reset() {
	*x = PaymentCreateRequest{}
	mi := &file_payment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentCreateRequest) ProtoMessage() {}

func (x *PaymentCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentCreateRequest.ProtoReflect.Descriptor instead.
func (*PaymentCreateRequest) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{0}
}

func (x *PaymentCreateRequest) GetAmount() float32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *PaymentCreateRequest) GetType() PaymentType {
	if x != nil {
		return x.Type
	}
	return PaymentType_PAYMENT_TYPE_QPAY
}

func (x *PaymentCreateRequest) GetMerchantId() uint64 {
	if x != nil {
		return x.MerchantId
	}
	return 0
}

func (x *PaymentCreateRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *PaymentCreateRequest) GetCustomerId() uint64 {
	if x != nil {
		return x.CustomerId
	}
	return 0
}

func (x *PaymentCreateRequest) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

type InvoiceResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BankInvoiceId string                 `protobuf:"bytes,1,opt,name=bank_invoice_id,json=bankInvoiceId,proto3" json:"bank_invoice_id,omitempty"`
	BankQrCode    string                 `protobuf:"bytes,2,opt,name=bank_qr_code,json=bankQrCode,proto3" json:"bank_qr_code,omitempty"`
	Deeplinks     []*Deeplink            `protobuf:"bytes,3,rep,name=deeplinks,proto3" json:"deeplinks,omitempty"`
	IsPaid        bool                   `protobuf:"varint,4,opt,name=is_paid,json=isPaid,proto3" json:"is_paid,omitempty"`
	Raw           *anypb.Any             `protobuf:"bytes,5,opt,name=raw,proto3" json:"raw,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvoiceResult) Reset() {
	*x = InvoiceResult{}
	mi := &file_payment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvoiceResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvoiceResult) ProtoMessage() {}

func (x *InvoiceResult) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvoiceResult.ProtoReflect.Descriptor instead.
func (*InvoiceResult) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{1}
}

func (x *InvoiceResult) GetBankInvoiceId() string {
	if x != nil {
		return x.BankInvoiceId
	}
	return ""
}

func (x *InvoiceResult) GetBankQrCode() string {
	if x != nil {
		return x.BankQrCode
	}
	return ""
}

func (x *InvoiceResult) GetDeeplinks() []*Deeplink {
	if x != nil {
		return x.Deeplinks
	}
	return nil
}

func (x *InvoiceResult) GetIsPaid() bool {
	if x != nil {
		return x.IsPaid
	}
	return false
}

func (x *InvoiceResult) GetRaw() *anypb.Any {
	if x != nil {
		return x.Raw
	}
	return nil
}

type Deeplink struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Link          string                 `protobuf:"bytes,3,opt,name=link,proto3" json:"link,omitempty"`
	Logo          string                 `protobuf:"bytes,4,opt,name=logo,proto3" json:"logo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Deeplink) Reset() {
	*x = Deeplink{}
	mi := &file_payment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Deeplink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Deeplink) ProtoMessage() {}

func (x *Deeplink) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Deeplink.ProtoReflect.Descriptor instead.
func (*Deeplink) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{2}
}

func (x *Deeplink) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Deeplink) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Deeplink) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *Deeplink) GetLogo() string {
	if x != nil {
		return x.Logo
	}
	return ""
}

type PaymentCreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	InvoiceResult *InvoiceResult         `protobuf:"bytes,2,opt,name=invoiceResult,proto3" json:"invoiceResult,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentCreateResponse) Reset() {
	*x = PaymentCreateResponse{}
	mi := &file_payment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentCreateResponse) ProtoMessage() {}

func (x *PaymentCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentCreateResponse.ProtoReflect.Descriptor instead.
func (*PaymentCreateResponse) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{3}
}

func (x *PaymentCreateResponse) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *PaymentCreateResponse) GetInvoiceResult() *InvoiceResult {
	if x != nil {
		return x.InvoiceResult
	}
	return nil
}

type PaymentCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentCheckRequest) Reset() {
	*x = PaymentCheckRequest{}
	mi := &file_payment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentCheckRequest) ProtoMessage() {}

func (x *PaymentCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentCheckRequest.ProtoReflect.Descriptor instead.
func (*PaymentCheckRequest) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{4}
}

func (x *PaymentCheckRequest) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

type PaymentCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Amount        float32                `protobuf:"fixed32,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Status        PaymentStatus          `protobuf:"varint,3,opt,name=status,proto3,enum=PaymentStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentCheckResponse) Reset() {
	*x = PaymentCheckResponse{}
	mi := &file_payment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentCheckResponse) ProtoMessage() {}

func (x *PaymentCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentCheckResponse.ProtoReflect.Descriptor instead.
func (*PaymentCheckResponse) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{5}
}

func (x *PaymentCheckResponse) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *PaymentCheckResponse) GetAmount() float32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *PaymentCheckResponse) GetStatus() PaymentStatus {
	if x != nil {
		return x.Status
	}
	return PaymentStatus_PAYMENT_STATUS_PENDING
}

var File_payment_proto protoreflect.FileDescriptor

const file_payment_proto_rawDesc = "" +
	"\n" +
	"\rpayment.proto\x1a\x19google/protobuf/any.proto\"\xbc\x01\n" +
	"\x14PaymentCreateRequest\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\x02R\x06amount\x12 \n" +
	"\x04type\x18\x05 \x01(\x0e2\f.PaymentTypeR\x04type\x12\x1f\n" +
	"\vmerchant_id\x18\x06 \x01(\x04R\n" +
	"merchantId\x12\x14\n" +
	"\x05phone\x18\a \x01(\tR\x05phone\x12\x1f\n" +
	"\vcustomer_id\x18\b \x01(\x04R\n" +
	"customerId\x12\x12\n" +
	"\x04note\x18\t \x01(\tR\x04note\"\xc3\x01\n" +
	"\rInvoiceResult\x12&\n" +
	"\x0fbank_invoice_id\x18\x01 \x01(\tR\rbankInvoiceId\x12 \n" +
	"\fbank_qr_code\x18\x02 \x01(\tR\n" +
	"bankQrCode\x12'\n" +
	"\tdeeplinks\x18\x03 \x03(\v2\t.DeeplinkR\tdeeplinks\x12\x17\n" +
	"\ais_paid\x18\x04 \x01(\bR\x06isPaid\x12&\n" +
	"\x03raw\x18\x05 \x01(\v2\x14.google.protobuf.AnyR\x03raw\"h\n" +
	"\bDeeplink\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x12\n" +
	"\x04link\x18\x03 \x01(\tR\x04link\x12\x12\n" +
	"\x04logo\x18\x04 \x01(\tR\x04logo\"_\n" +
	"\x15PaymentCreateResponse\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\x124\n" +
	"\rinvoiceResult\x18\x02 \x01(\v2\x0e.InvoiceResultR\rinvoiceResult\"'\n" +
	"\x13PaymentCheckRequest\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\"h\n" +
	"\x14PaymentCheckResponse\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x02R\x06amount\x12&\n" +
	"\x06status\x18\x03 \x01(\x0e2\x0e.PaymentStatusR\x06status*\x7f\n" +
	"\rPaymentStatus\x12\x1a\n" +
	"\x16PAYMENT_STATUS_PENDING\x10\x00\x12\x17\n" +
	"\x13PAYMENT_STATUS_PAID\x10\x01\x12\x1c\n" +
	"\x18PAYMENT_STATUS_CANCELLED\x10\x02\x12\x1b\n" +
	"\x17PAYMENT_STATUS_REFUNDED\x10\x03*\xf0\x01\n" +
	"\vPaymentType\x12\x15\n" +
	"\x11PAYMENT_TYPE_QPAY\x10\x00\x12\x18\n" +
	"\x14PAYMENT_TYPE_TOKIPAY\x10\x01\x12\x17\n" +
	"\x13PAYMENT_TYPE_MONPAY\x10\x02\x12\x17\n" +
	"\x13PAYMENT_TYPE_GOLOMT\x10\x03\x12\x1a\n" +
	"\x16PAYMENT_TYPE_SOCIALPAY\x10\x04\x12\x19\n" +
	"\x15PAYMENT_TYPE_STOREPAY\x10\x05\x12\x17\n" +
	"\x13PAYMENT_TYPE_POCKET\x10\x06\x12\x17\n" +
	"\x13PAYMENT_TYPE_SIMPLE\x10\a\x12\x15\n" +
	"\x11PAYMENT_TYPE_BALC\x10\b2\xbd\x01\n" +
	"\x0ePaymentService\x127\n" +
	"\x06Create\x12\x15.PaymentCreateRequest\x1a\x16.PaymentCreateResponse\x124\n" +
	"\x05Check\x12\x14.PaymentCheckRequest\x1a\x15.PaymentCheckResponse\x12<\n" +
	"\vCheckStream\x12\x14.PaymentCheckRequest\x1a\x15.PaymentCheckResponse0\x01B\x03Z\x01.b\x06proto3"

var (
	file_payment_proto_rawDescOnce sync.Once
	file_payment_proto_rawDescData []byte
)

func file_payment_proto_rawDescGZIP() []byte {
	file_payment_proto_rawDescOnce.Do(func() {
		file_payment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_payment_proto_rawDesc), len(file_payment_proto_rawDesc)))
	})
	return file_payment_proto_rawDescData
}

var file_payment_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_payment_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_payment_proto_goTypes = []any{
	(PaymentStatus)(0),            // 0: PaymentStatus
	(PaymentType)(0),              // 1: PaymentType
	(*PaymentCreateRequest)(nil),  // 2: PaymentCreateRequest
	(*InvoiceResult)(nil),         // 3: InvoiceResult
	(*Deeplink)(nil),              // 4: Deeplink
	(*PaymentCreateResponse)(nil), // 5: PaymentCreateResponse
	(*PaymentCheckRequest)(nil),   // 6: PaymentCheckRequest
	(*PaymentCheckResponse)(nil),  // 7: PaymentCheckResponse
	(*anypb.Any)(nil),             // 8: google.protobuf.Any
}
var file_payment_proto_depIdxs = []int32{
	1, // 0: PaymentCreateRequest.type:type_name -> PaymentType
	4, // 1: InvoiceResult.deeplinks:type_name -> Deeplink
	8, // 2: InvoiceResult.raw:type_name -> google.protobuf.Any
	3, // 3: PaymentCreateResponse.invoiceResult:type_name -> InvoiceResult
	0, // 4: PaymentCheckResponse.status:type_name -> PaymentStatus
	2, // 5: PaymentService.Create:input_type -> PaymentCreateRequest
	6, // 6: PaymentService.Check:input_type -> PaymentCheckRequest
	6, // 7: PaymentService.CheckStream:input_type -> PaymentCheckRequest
	5, // 8: PaymentService.Create:output_type -> PaymentCreateResponse
	7, // 9: PaymentService.Check:output_type -> PaymentCheckResponse
	7, // 10: PaymentService.CheckStream:output_type -> PaymentCheckResponse
	8, // [8:11] is the sub-list for method output_type
	5, // [5:8] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_payment_proto_init() }
func file_payment_proto_init() {
	if File_payment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_payment_proto_rawDesc), len(file_payment_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_payment_proto_goTypes,
		DependencyIndexes: file_payment_proto_depIdxs,
		EnumInfos:         file_payment_proto_enumTypes,
		MessageInfos:      file_payment_proto_msgTypes,
	}.Build()
	File_payment_proto = out.File
	file_payment_proto_goTypes = nil
	file_payment_proto_depIdxs = nil
}
