// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.0
// source: merchant.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QpayAdapterProto struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// QpayAdapter struct
	Username      string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Endpoint      string `protobuf:"bytes,3,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Callback      string `protobuf:"bytes,4,opt,name=callback,proto3" json:"callback,omitempty"`
	InvoiceCode   string `protobuf:"bytes,5,opt,name=invoice_code,json=invoiceCode,proto3" json:"invoice_code,omitempty"`
	MerchantId    string `protobuf:"bytes,6,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QpayAdapterProto) Reset() {
	*x = QpayAdapterProto{}
	mi := &file_merchant_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QpayAdapterProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QpayAdapterProto) ProtoMessage() {}

func (x *QpayAdapterProto) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QpayAdapterProto.ProtoReflect.Descriptor instead.
func (*QpayAdapterProto) Descriptor() ([]byte, []int) {
	return file_merchant_proto_rawDescGZIP(), []int{0}
}

func (x *QpayAdapterProto) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *QpayAdapterProto) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *QpayAdapterProto) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *QpayAdapterProto) GetCallback() string {
	if x != nil {
		return x.Callback
	}
	return ""
}

func (x *QpayAdapterProto) GetInvoiceCode() string {
	if x != nil {
		return x.InvoiceCode
	}
	return ""
}

func (x *QpayAdapterProto) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

type TokipayAdapterProto struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// TokipayAdapter struct
	Endpoint      string `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	ApiKey        string `protobuf:"bytes,2,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	ImApiKey      string `protobuf:"bytes,3,opt,name=im_api_key,json=imApiKey,proto3" json:"im_api_key,omitempty"`
	Authorization string `protobuf:"bytes,4,opt,name=authorization,proto3" json:"authorization,omitempty"`
	MerchantId    string `protobuf:"bytes,5,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	SuccessUrl    string `protobuf:"bytes,6,opt,name=success_url,json=successUrl,proto3" json:"success_url,omitempty"`
	FailureUrl    string `protobuf:"bytes,7,opt,name=failure_url,json=failureUrl,proto3" json:"failure_url,omitempty"`
	AppSchemaIos  string `protobuf:"bytes,8,opt,name=app_schema_ios,json=appSchemaIos,proto3" json:"app_schema_ios,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokipayAdapterProto) Reset() {
	*x = TokipayAdapterProto{}
	mi := &file_merchant_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokipayAdapterProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokipayAdapterProto) ProtoMessage() {}

func (x *TokipayAdapterProto) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokipayAdapterProto.ProtoReflect.Descriptor instead.
func (*TokipayAdapterProto) Descriptor() ([]byte, []int) {
	return file_merchant_proto_rawDescGZIP(), []int{1}
}

func (x *TokipayAdapterProto) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *TokipayAdapterProto) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *TokipayAdapterProto) GetImApiKey() string {
	if x != nil {
		return x.ImApiKey
	}
	return ""
}

func (x *TokipayAdapterProto) GetAuthorization() string {
	if x != nil {
		return x.Authorization
	}
	return ""
}

func (x *TokipayAdapterProto) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *TokipayAdapterProto) GetSuccessUrl() string {
	if x != nil {
		return x.SuccessUrl
	}
	return ""
}

func (x *TokipayAdapterProto) GetFailureUrl() string {
	if x != nil {
		return x.FailureUrl
	}
	return ""
}

func (x *TokipayAdapterProto) GetAppSchemaIos() string {
	if x != nil {
		return x.AppSchemaIos
	}
	return ""
}

type StorePayAdapterProto struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// StorePayAdapter struct
	AppUserName   string `protobuf:"bytes,1,opt,name=app_user_name,json=appUserName,proto3" json:"app_user_name,omitempty"`
	AppPassword   string `protobuf:"bytes,2,opt,name=app_password,json=appPassword,proto3" json:"app_password,omitempty"`
	Username      string `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Password      string `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	AuthUrl       string `protobuf:"bytes,5,opt,name=auth_url,json=authUrl,proto3" json:"auth_url,omitempty"`
	BaseUrl       string `protobuf:"bytes,6,opt,name=base_url,json=baseUrl,proto3" json:"base_url,omitempty"`
	StoreId       string `protobuf:"bytes,7,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	CallbackUrl   string `protobuf:"bytes,8,opt,name=callback_url,json=callbackUrl,proto3" json:"callback_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StorePayAdapterProto) Reset() {
	*x = StorePayAdapterProto{}
	mi := &file_merchant_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorePayAdapterProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorePayAdapterProto) ProtoMessage() {}

func (x *StorePayAdapterProto) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorePayAdapterProto.ProtoReflect.Descriptor instead.
func (*StorePayAdapterProto) Descriptor() ([]byte, []int) {
	return file_merchant_proto_rawDescGZIP(), []int{2}
}

func (x *StorePayAdapterProto) GetAppUserName() string {
	if x != nil {
		return x.AppUserName
	}
	return ""
}

func (x *StorePayAdapterProto) GetAppPassword() string {
	if x != nil {
		return x.AppPassword
	}
	return ""
}

func (x *StorePayAdapterProto) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *StorePayAdapterProto) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *StorePayAdapterProto) GetAuthUrl() string {
	if x != nil {
		return x.AuthUrl
	}
	return ""
}

func (x *StorePayAdapterProto) GetBaseUrl() string {
	if x != nil {
		return x.BaseUrl
	}
	return ""
}

func (x *StorePayAdapterProto) GetStoreId() string {
	if x != nil {
		return x.StoreId
	}
	return ""
}

func (x *StorePayAdapterProto) GetCallbackUrl() string {
	if x != nil {
		return x.CallbackUrl
	}
	return ""
}

type SocialPayAdapterProto struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// SocialPayAdapter struct
	Terminal      string `protobuf:"bytes,1,opt,name=terminal,proto3" json:"terminal,omitempty"`
	Secret        string `protobuf:"bytes,2,opt,name=secret,proto3" json:"secret,omitempty"`
	Endpoint      string `protobuf:"bytes,3,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SocialPayAdapterProto) Reset() {
	*x = SocialPayAdapterProto{}
	mi := &file_merchant_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SocialPayAdapterProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SocialPayAdapterProto) ProtoMessage() {}

func (x *SocialPayAdapterProto) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SocialPayAdapterProto.ProtoReflect.Descriptor instead.
func (*SocialPayAdapterProto) Descriptor() ([]byte, []int) {
	return file_merchant_proto_rawDescGZIP(), []int{3}
}

func (x *SocialPayAdapterProto) GetTerminal() string {
	if x != nil {
		return x.Terminal
	}
	return ""
}

func (x *SocialPayAdapterProto) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

func (x *SocialPayAdapterProto) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

type PocketAdapterProto struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// PocketAdapter struct
	Merchant      string `protobuf:"bytes,1,opt,name=merchant,proto3" json:"merchant,omitempty"`
	ClientId      string `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	ClientSecret  string `protobuf:"bytes,3,opt,name=client_secret,json=clientSecret,proto3" json:"client_secret,omitempty"`
	Environment   string `protobuf:"bytes,4,opt,name=environment,proto3" json:"environment,omitempty"`
	TerminalIdRaw int64  `protobuf:"varint,5,opt,name=terminal_id_raw,json=terminalIdRaw,proto3" json:"terminal_id_raw,omitempty"` // Mapped to int64
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PocketAdapterProto) Reset() {
	*x = PocketAdapterProto{}
	mi := &file_merchant_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PocketAdapterProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PocketAdapterProto) ProtoMessage() {}

func (x *PocketAdapterProto) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PocketAdapterProto.ProtoReflect.Descriptor instead.
func (*PocketAdapterProto) Descriptor() ([]byte, []int) {
	return file_merchant_proto_rawDescGZIP(), []int{4}
}

func (x *PocketAdapterProto) GetMerchant() string {
	if x != nil {
		return x.Merchant
	}
	return ""
}

func (x *PocketAdapterProto) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *PocketAdapterProto) GetClientSecret() string {
	if x != nil {
		return x.ClientSecret
	}
	return ""
}

func (x *PocketAdapterProto) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

func (x *PocketAdapterProto) GetTerminalIdRaw() int64 {
	if x != nil {
		return x.TerminalIdRaw
	}
	return 0
}

type MonpayAdapterProto struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// MonpayAdapter struct
	Endpoint      string `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Username      string `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	AccountId     string `protobuf:"bytes,3,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Callback      string `protobuf:"bytes,4,opt,name=callback,proto3" json:"callback,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MonpayAdapterProto) Reset() {
	*x = MonpayAdapterProto{}
	mi := &file_merchant_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonpayAdapterProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonpayAdapterProto) ProtoMessage() {}

func (x *MonpayAdapterProto) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonpayAdapterProto.ProtoReflect.Descriptor instead.
func (*MonpayAdapterProto) Descriptor() ([]byte, []int) {
	return file_merchant_proto_rawDescGZIP(), []int{5}
}

func (x *MonpayAdapterProto) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *MonpayAdapterProto) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *MonpayAdapterProto) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *MonpayAdapterProto) GetCallback() string {
	if x != nil {
		return x.Callback
	}
	return ""
}

type GolomtAdapterProto struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// GolomtAdapter struct
	BaseUrl       string `protobuf:"bytes,1,opt,name=base_url,json=baseUrl,proto3" json:"base_url,omitempty"`
	Secret        string `protobuf:"bytes,2,opt,name=secret,proto3" json:"secret,omitempty"`
	BearerToken   string `protobuf:"bytes,3,opt,name=bearer_token,json=bearerToken,proto3" json:"bearer_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GolomtAdapterProto) Reset() {
	*x = GolomtAdapterProto{}
	mi := &file_merchant_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GolomtAdapterProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GolomtAdapterProto) ProtoMessage() {}

func (x *GolomtAdapterProto) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GolomtAdapterProto.ProtoReflect.Descriptor instead.
func (*GolomtAdapterProto) Descriptor() ([]byte, []int) {
	return file_merchant_proto_rawDescGZIP(), []int{6}
}

func (x *GolomtAdapterProto) GetBaseUrl() string {
	if x != nil {
		return x.BaseUrl
	}
	return ""
}

func (x *GolomtAdapterProto) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

func (x *GolomtAdapterProto) GetBearerToken() string {
	if x != nil {
		return x.BearerToken
	}
	return ""
}

type BalcAdapterProto struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// BalcAdapter struct
	Endpoint      string `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Token         string `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BalcAdapterProto) Reset() {
	*x = BalcAdapterProto{}
	mi := &file_merchant_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BalcAdapterProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BalcAdapterProto) ProtoMessage() {}

func (x *BalcAdapterProto) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BalcAdapterProto.ProtoReflect.Descriptor instead.
func (*BalcAdapterProto) Descriptor() ([]byte, []int) {
	return file_merchant_proto_rawDescGZIP(), []int{7}
}

func (x *BalcAdapterProto) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *BalcAdapterProto) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type SimpleAdapterProto struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// SimpleAdapter struct
	UserName      string `protobuf:"bytes,1,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	Password      string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	BaseUrl       string `protobuf:"bytes,3,opt,name=base_url,json=baseUrl,proto3" json:"base_url,omitempty"`
	CallbackUrl   string `protobuf:"bytes,4,opt,name=callback_url,json=callbackUrl,proto3" json:"callback_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimpleAdapterProto) Reset() {
	*x = SimpleAdapterProto{}
	mi := &file_merchant_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimpleAdapterProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimpleAdapterProto) ProtoMessage() {}

func (x *SimpleAdapterProto) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimpleAdapterProto.ProtoReflect.Descriptor instead.
func (*SimpleAdapterProto) Descriptor() ([]byte, []int) {
	return file_merchant_proto_rawDescGZIP(), []int{8}
}

func (x *SimpleAdapterProto) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *SimpleAdapterProto) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *SimpleAdapterProto) GetBaseUrl() string {
	if x != nil {
		return x.BaseUrl
	}
	return ""
}

func (x *SimpleAdapterProto) GetCallbackUrl() string {
	if x != nil {
		return x.CallbackUrl
	}
	return ""
}

type MerchantEbarimtCredentialRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Tin           string                 `protobuf:"bytes,2,opt,name=tin,proto3" json:"tin,omitempty"`
	PosNo         string                 `protobuf:"bytes,3,opt,name=posNo,proto3" json:"posNo,omitempty"`
	BranchNo      string                 `protobuf:"bytes,4,opt,name=branchNo,proto3" json:"branchNo,omitempty"`
	DistrictCode  string                 `protobuf:"bytes,5,opt,name=districtCode,proto3" json:"districtCode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MerchantEbarimtCredentialRequest) Reset() {
	*x = MerchantEbarimtCredentialRequest{}
	mi := &file_merchant_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MerchantEbarimtCredentialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MerchantEbarimtCredentialRequest) ProtoMessage() {}

func (x *MerchantEbarimtCredentialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MerchantEbarimtCredentialRequest.ProtoReflect.Descriptor instead.
func (*MerchantEbarimtCredentialRequest) Descriptor() ([]byte, []int) {
	return file_merchant_proto_rawDescGZIP(), []int{9}
}

func (x *MerchantEbarimtCredentialRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *MerchantEbarimtCredentialRequest) GetTin() string {
	if x != nil {
		return x.Tin
	}
	return ""
}

func (x *MerchantEbarimtCredentialRequest) GetPosNo() string {
	if x != nil {
		return x.PosNo
	}
	return ""
}

func (x *MerchantEbarimtCredentialRequest) GetBranchNo() string {
	if x != nil {
		return x.BranchNo
	}
	return ""
}

func (x *MerchantEbarimtCredentialRequest) GetDistrictCode() string {
	if x != nil {
		return x.DistrictCode
	}
	return ""
}

type MerchantPaymentCredentialRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Qpay          *QpayAdapterProto      `protobuf:"bytes,1,opt,name=qpay,proto3" json:"qpay,omitempty"`
	Tokipay       *TokipayAdapterProto   `protobuf:"bytes,2,opt,name=tokipay,proto3" json:"tokipay,omitempty"`
	Balc          *BalcAdapterProto      `protobuf:"bytes,3,opt,name=balc,proto3" json:"balc,omitempty"`
	Storepay      *StorePayAdapterProto  `protobuf:"bytes,4,opt,name=storepay,proto3" json:"storepay,omitempty"`
	Socialpay     *SocialPayAdapterProto `protobuf:"bytes,5,opt,name=socialpay,proto3" json:"socialpay,omitempty"`
	Simple        *SimpleAdapterProto    `protobuf:"bytes,6,opt,name=simple,proto3" json:"simple,omitempty"`
	Pocket        *PocketAdapterProto    `protobuf:"bytes,7,opt,name=pocket,proto3" json:"pocket,omitempty"`
	Monpay        *MonpayAdapterProto    `protobuf:"bytes,8,opt,name=monpay,proto3" json:"monpay,omitempty"`
	Golomt        *GolomtAdapterProto    `protobuf:"bytes,9,opt,name=golomt,proto3" json:"golomt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MerchantPaymentCredentialRequest) Reset() {
	*x = MerchantPaymentCredentialRequest{}
	mi := &file_merchant_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MerchantPaymentCredentialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MerchantPaymentCredentialRequest) ProtoMessage() {}

func (x *MerchantPaymentCredentialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MerchantPaymentCredentialRequest.ProtoReflect.Descriptor instead.
func (*MerchantPaymentCredentialRequest) Descriptor() ([]byte, []int) {
	return file_merchant_proto_rawDescGZIP(), []int{10}
}

func (x *MerchantPaymentCredentialRequest) GetQpay() *QpayAdapterProto {
	if x != nil {
		return x.Qpay
	}
	return nil
}

func (x *MerchantPaymentCredentialRequest) GetTokipay() *TokipayAdapterProto {
	if x != nil {
		return x.Tokipay
	}
	return nil
}

func (x *MerchantPaymentCredentialRequest) GetBalc() *BalcAdapterProto {
	if x != nil {
		return x.Balc
	}
	return nil
}

func (x *MerchantPaymentCredentialRequest) GetStorepay() *StorePayAdapterProto {
	if x != nil {
		return x.Storepay
	}
	return nil
}

func (x *MerchantPaymentCredentialRequest) GetSocialpay() *SocialPayAdapterProto {
	if x != nil {
		return x.Socialpay
	}
	return nil
}

func (x *MerchantPaymentCredentialRequest) GetSimple() *SimpleAdapterProto {
	if x != nil {
		return x.Simple
	}
	return nil
}

func (x *MerchantPaymentCredentialRequest) GetPocket() *PocketAdapterProto {
	if x != nil {
		return x.Pocket
	}
	return nil
}

func (x *MerchantPaymentCredentialRequest) GetMonpay() *MonpayAdapterProto {
	if x != nil {
		return x.Monpay
	}
	return nil
}

func (x *MerchantPaymentCredentialRequest) GetGolomt() *GolomtAdapterProto {
	if x != nil {
		return x.Golomt
	}
	return nil
}

type MerchantPaymentCredentialResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MerchantPaymentCredentialResponse) Reset() {
	*x = MerchantPaymentCredentialResponse{}
	mi := &file_merchant_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MerchantPaymentCredentialResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MerchantPaymentCredentialResponse) ProtoMessage() {}

func (x *MerchantPaymentCredentialResponse) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MerchantPaymentCredentialResponse.ProtoReflect.Descriptor instead.
func (*MerchantPaymentCredentialResponse) Descriptor() ([]byte, []int) {
	return file_merchant_proto_rawDescGZIP(), []int{11}
}

func (x *MerchantPaymentCredentialResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type MerchantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MerchantResponse) Reset() {
	*x = MerchantResponse{}
	mi := &file_merchant_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MerchantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MerchantResponse) ProtoMessage() {}

func (x *MerchantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MerchantResponse.ProtoReflect.Descriptor instead.
func (*MerchantResponse) Descriptor() ([]byte, []int) {
	return file_merchant_proto_rawDescGZIP(), []int{12}
}

func (x *MerchantResponse) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *MerchantResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateMerchantRequest struct {
	state             protoimpl.MessageState            `protogen:"open.v1"`
	Name              string                            `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Uid               string                            `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	EbarimtCredential *MerchantEbarimtCredentialRequest `protobuf:"bytes,3,opt,name=ebarimtCredential,proto3" json:"ebarimtCredential,omitempty"`
	PaymentCredential *MerchantPaymentCredentialRequest `protobuf:"bytes,4,opt,name=paymentCredential,proto3" json:"paymentCredential,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreateMerchantRequest) Reset() {
	*x = CreateMerchantRequest{}
	mi := &file_merchant_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMerchantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMerchantRequest) ProtoMessage() {}

func (x *CreateMerchantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMerchantRequest.ProtoReflect.Descriptor instead.
func (*CreateMerchantRequest) Descriptor() ([]byte, []int) {
	return file_merchant_proto_rawDescGZIP(), []int{13}
}

func (x *CreateMerchantRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateMerchantRequest) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *CreateMerchantRequest) GetEbarimtCredential() *MerchantEbarimtCredentialRequest {
	if x != nil {
		return x.EbarimtCredential
	}
	return nil
}

func (x *CreateMerchantRequest) GetPaymentCredential() *MerchantPaymentCredentialRequest {
	if x != nil {
		return x.PaymentCredential
	}
	return nil
}

type UpdateRequest struct {
	state             protoimpl.MessageState            `protogen:"open.v1"`
	Uid               string                            `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Name              string                            `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	EbarimtCredential *MerchantEbarimtCredentialRequest `protobuf:"bytes,3,opt,name=ebarimtCredential,proto3" json:"ebarimtCredential,omitempty"`
	PaymentCredential *MerchantPaymentCredentialRequest `protobuf:"bytes,4,opt,name=paymentCredential,proto3" json:"paymentCredential,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UpdateRequest) Reset() {
	*x = UpdateRequest{}
	mi := &file_merchant_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequest) ProtoMessage() {}

func (x *UpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRequest.ProtoReflect.Descriptor instead.
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return file_merchant_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateRequest) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *UpdateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateRequest) GetEbarimtCredential() *MerchantEbarimtCredentialRequest {
	if x != nil {
		return x.EbarimtCredential
	}
	return nil
}

func (x *UpdateRequest) GetPaymentCredential() *MerchantPaymentCredentialRequest {
	if x != nil {
		return x.PaymentCredential
	}
	return nil
}

type MerchantIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MerchantIDRequest) Reset() {
	*x = MerchantIDRequest{}
	mi := &file_merchant_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MerchantIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MerchantIDRequest) ProtoMessage() {}

func (x *MerchantIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MerchantIDRequest.ProtoReflect.Descriptor instead.
func (*MerchantIDRequest) Descriptor() ([]byte, []int) {
	return file_merchant_proto_rawDescGZIP(), []int{15}
}

func (x *MerchantIDRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type SuccessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuccessResponse) Reset() {
	*x = SuccessResponse{}
	mi := &file_merchant_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuccessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuccessResponse) ProtoMessage() {}

func (x *SuccessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuccessResponse.ProtoReflect.Descriptor instead.
func (*SuccessResponse) Descriptor() ([]byte, []int) {
	return file_merchant_proto_rawDescGZIP(), []int{16}
}

func (x *SuccessResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_merchant_proto protoreflect.FileDescriptor

const file_merchant_proto_rawDesc = "" +
	"\n" +
	"\x0emerchant.proto\"\xc6\x01\n" +
	"\x10QpayAdapterProto\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x1a\n" +
	"\bendpoint\x18\x03 \x01(\tR\bendpoint\x12\x1a\n" +
	"\bcallback\x18\x04 \x01(\tR\bcallback\x12!\n" +
	"\finvoice_code\x18\x05 \x01(\tR\vinvoiceCode\x12\x1f\n" +
	"\vmerchant_id\x18\x06 \x01(\tR\n" +
	"merchantId\"\x97\x02\n" +
	"\x13TokipayAdapterProto\x12\x1a\n" +
	"\bendpoint\x18\x01 \x01(\tR\bendpoint\x12\x17\n" +
	"\aapi_key\x18\x02 \x01(\tR\x06apiKey\x12\x1c\n" +
	"\n" +
	"im_api_key\x18\x03 \x01(\tR\bimApiKey\x12$\n" +
	"\rauthorization\x18\x04 \x01(\tR\rauthorization\x12\x1f\n" +
	"\vmerchant_id\x18\x05 \x01(\tR\n" +
	"merchantId\x12\x1f\n" +
	"\vsuccess_url\x18\x06 \x01(\tR\n" +
	"successUrl\x12\x1f\n" +
	"\vfailure_url\x18\a \x01(\tR\n" +
	"failureUrl\x12$\n" +
	"\x0eapp_schema_ios\x18\b \x01(\tR\fappSchemaIos\"\x89\x02\n" +
	"\x14StorePayAdapterProto\x12\"\n" +
	"\rapp_user_name\x18\x01 \x01(\tR\vappUserName\x12!\n" +
	"\fapp_password\x18\x02 \x01(\tR\vappPassword\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\x12\x19\n" +
	"\bauth_url\x18\x05 \x01(\tR\aauthUrl\x12\x19\n" +
	"\bbase_url\x18\x06 \x01(\tR\abaseUrl\x12\x19\n" +
	"\bstore_id\x18\a \x01(\tR\astoreId\x12!\n" +
	"\fcallback_url\x18\b \x01(\tR\vcallbackUrl\"g\n" +
	"\x15SocialPayAdapterProto\x12\x1a\n" +
	"\bterminal\x18\x01 \x01(\tR\bterminal\x12\x16\n" +
	"\x06secret\x18\x02 \x01(\tR\x06secret\x12\x1a\n" +
	"\bendpoint\x18\x03 \x01(\tR\bendpoint\"\xbc\x01\n" +
	"\x12PocketAdapterProto\x12\x1a\n" +
	"\bmerchant\x18\x01 \x01(\tR\bmerchant\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\x12#\n" +
	"\rclient_secret\x18\x03 \x01(\tR\fclientSecret\x12 \n" +
	"\venvironment\x18\x04 \x01(\tR\venvironment\x12&\n" +
	"\x0fterminal_id_raw\x18\x05 \x01(\x03R\rterminalIdRaw\"\x87\x01\n" +
	"\x12MonpayAdapterProto\x12\x1a\n" +
	"\bendpoint\x18\x01 \x01(\tR\bendpoint\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1d\n" +
	"\n" +
	"account_id\x18\x03 \x01(\tR\taccountId\x12\x1a\n" +
	"\bcallback\x18\x04 \x01(\tR\bcallback\"j\n" +
	"\x12GolomtAdapterProto\x12\x19\n" +
	"\bbase_url\x18\x01 \x01(\tR\abaseUrl\x12\x16\n" +
	"\x06secret\x18\x02 \x01(\tR\x06secret\x12!\n" +
	"\fbearer_token\x18\x03 \x01(\tR\vbearerToken\"D\n" +
	"\x10BalcAdapterProto\x12\x1a\n" +
	"\bendpoint\x18\x01 \x01(\tR\bendpoint\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\"\x8b\x01\n" +
	"\x12SimpleAdapterProto\x12\x1b\n" +
	"\tuser_name\x18\x01 \x01(\tR\buserName\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x19\n" +
	"\bbase_url\x18\x03 \x01(\tR\abaseUrl\x12!\n" +
	"\fcallback_url\x18\x04 \x01(\tR\vcallbackUrl\"\x9c\x01\n" +
	" MerchantEbarimtCredentialRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x10\n" +
	"\x03tin\x18\x02 \x01(\tR\x03tin\x12\x14\n" +
	"\x05posNo\x18\x03 \x01(\tR\x05posNo\x12\x1a\n" +
	"\bbranchNo\x18\x04 \x01(\tR\bbranchNo\x12\"\n" +
	"\fdistrictCode\x18\x05 \x01(\tR\fdistrictCode\"\xbd\x03\n" +
	" MerchantPaymentCredentialRequest\x12%\n" +
	"\x04qpay\x18\x01 \x01(\v2\x11.QpayAdapterProtoR\x04qpay\x12.\n" +
	"\atokipay\x18\x02 \x01(\v2\x14.TokipayAdapterProtoR\atokipay\x12%\n" +
	"\x04balc\x18\x03 \x01(\v2\x11.BalcAdapterProtoR\x04balc\x121\n" +
	"\bstorepay\x18\x04 \x01(\v2\x15.StorePayAdapterProtoR\bstorepay\x124\n" +
	"\tsocialpay\x18\x05 \x01(\v2\x16.SocialPayAdapterProtoR\tsocialpay\x12+\n" +
	"\x06simple\x18\x06 \x01(\v2\x13.SimpleAdapterProtoR\x06simple\x12+\n" +
	"\x06pocket\x18\a \x01(\v2\x13.PocketAdapterProtoR\x06pocket\x12+\n" +
	"\x06monpay\x18\b \x01(\v2\x13.MonpayAdapterProtoR\x06monpay\x12+\n" +
	"\x06golomt\x18\t \x01(\v2\x13.GolomtAdapterProtoR\x06golomt\"9\n" +
	"!MerchantPaymentCredentialResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"8\n" +
	"\x10MerchantResponse\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\xdf\x01\n" +
	"\x15CreateMerchantRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\tR\x03uid\x12O\n" +
	"\x11ebarimtCredential\x18\x03 \x01(\v2!.MerchantEbarimtCredentialRequestR\x11ebarimtCredential\x12O\n" +
	"\x11paymentCredential\x18\x04 \x01(\v2!.MerchantPaymentCredentialRequestR\x11paymentCredential\"\xd7\x01\n" +
	"\rUpdateRequest\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12O\n" +
	"\x11ebarimtCredential\x18\x03 \x01(\v2!.MerchantEbarimtCredentialRequestR\x11ebarimtCredential\x12O\n" +
	"\x11paymentCredential\x18\x04 \x01(\v2!.MerchantPaymentCredentialRequestR\x11paymentCredential\"#\n" +
	"\x11MerchantIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"+\n" +
	"\x0fSuccessResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xd3\x01\n" +
	"\x0fMerchantService\x122\n" +
	"\x06Create\x12\x16.CreateMerchantRequest\x1a\x10.SuccessResponse\x120\n" +
	"\aGetByID\x12\x12.MerchantIDRequest\x1a\x11.MerchantResponse\x12*\n" +
	"\x06Update\x12\x0e.UpdateRequest\x1a\x10.SuccessResponse\x12.\n" +
	"\x06Delete\x12\x12.MerchantIDRequest\x1a\x10.SuccessResponseB\x03Z\x01.b\x06proto3"

var (
	file_merchant_proto_rawDescOnce sync.Once
	file_merchant_proto_rawDescData []byte
)

func file_merchant_proto_rawDescGZIP() []byte {
	file_merchant_proto_rawDescOnce.Do(func() {
		file_merchant_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_merchant_proto_rawDesc), len(file_merchant_proto_rawDesc)))
	})
	return file_merchant_proto_rawDescData
}

var file_merchant_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_merchant_proto_goTypes = []any{
	(*QpayAdapterProto)(nil),                  // 0: QpayAdapterProto
	(*TokipayAdapterProto)(nil),               // 1: TokipayAdapterProto
	(*StorePayAdapterProto)(nil),              // 2: StorePayAdapterProto
	(*SocialPayAdapterProto)(nil),             // 3: SocialPayAdapterProto
	(*PocketAdapterProto)(nil),                // 4: PocketAdapterProto
	(*MonpayAdapterProto)(nil),                // 5: MonpayAdapterProto
	(*GolomtAdapterProto)(nil),                // 6: GolomtAdapterProto
	(*BalcAdapterProto)(nil),                  // 7: BalcAdapterProto
	(*SimpleAdapterProto)(nil),                // 8: SimpleAdapterProto
	(*MerchantEbarimtCredentialRequest)(nil),  // 9: MerchantEbarimtCredentialRequest
	(*MerchantPaymentCredentialRequest)(nil),  // 10: MerchantPaymentCredentialRequest
	(*MerchantPaymentCredentialResponse)(nil), // 11: MerchantPaymentCredentialResponse
	(*MerchantResponse)(nil),                  // 12: MerchantResponse
	(*CreateMerchantRequest)(nil),             // 13: CreateMerchantRequest
	(*UpdateRequest)(nil),                     // 14: UpdateRequest
	(*MerchantIDRequest)(nil),                 // 15: MerchantIDRequest
	(*SuccessResponse)(nil),                   // 16: SuccessResponse
}
var file_merchant_proto_depIdxs = []int32{
	0,  // 0: MerchantPaymentCredentialRequest.qpay:type_name -> QpayAdapterProto
	1,  // 1: MerchantPaymentCredentialRequest.tokipay:type_name -> TokipayAdapterProto
	7,  // 2: MerchantPaymentCredentialRequest.balc:type_name -> BalcAdapterProto
	2,  // 3: MerchantPaymentCredentialRequest.storepay:type_name -> StorePayAdapterProto
	3,  // 4: MerchantPaymentCredentialRequest.socialpay:type_name -> SocialPayAdapterProto
	8,  // 5: MerchantPaymentCredentialRequest.simple:type_name -> SimpleAdapterProto
	4,  // 6: MerchantPaymentCredentialRequest.pocket:type_name -> PocketAdapterProto
	5,  // 7: MerchantPaymentCredentialRequest.monpay:type_name -> MonpayAdapterProto
	6,  // 8: MerchantPaymentCredentialRequest.golomt:type_name -> GolomtAdapterProto
	9,  // 9: CreateMerchantRequest.ebarimtCredential:type_name -> MerchantEbarimtCredentialRequest
	10, // 10: CreateMerchantRequest.paymentCredential:type_name -> MerchantPaymentCredentialRequest
	9,  // 11: UpdateRequest.ebarimtCredential:type_name -> MerchantEbarimtCredentialRequest
	10, // 12: UpdateRequest.paymentCredential:type_name -> MerchantPaymentCredentialRequest
	13, // 13: MerchantService.Create:input_type -> CreateMerchantRequest
	15, // 14: MerchantService.GetByID:input_type -> MerchantIDRequest
	14, // 15: MerchantService.Update:input_type -> UpdateRequest
	15, // 16: MerchantService.Delete:input_type -> MerchantIDRequest
	16, // 17: MerchantService.Create:output_type -> SuccessResponse
	12, // 18: MerchantService.GetByID:output_type -> MerchantResponse
	16, // 19: MerchantService.Update:output_type -> SuccessResponse
	16, // 20: MerchantService.Delete:output_type -> SuccessResponse
	17, // [17:21] is the sub-list for method output_type
	13, // [13:17] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_merchant_proto_init() }
func file_merchant_proto_init() {
	if File_merchant_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_merchant_proto_rawDesc), len(file_merchant_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_merchant_proto_goTypes,
		DependencyIndexes: file_merchant_proto_depIdxs,
		MessageInfos:      file_merchant_proto_msgTypes,
	}.Build()
	File_merchant_proto = out.File
	file_merchant_proto_goTypes = nil
	file_merchant_proto_depIdxs = nil
}
